# questions.toml
[[questions]]
pregunta = "Que tipo de dominio separa una VLAN"
respuesta = "broadcast"
opciones = ["colision", "multicast", "unicast"]

[[questions]]
pregunta = "Que direccionamiento es utilizado en la capa 3 del modelo OSI"
respuesta = "ip"
opciones = ["mac-address", "netbios", "serial"]

[[questions]]
pregunta = "Que dispositivo communta tramas y separa dominios de colision"
respuesta = "switch"
opciones = ["router", "hub", "firewall"]

[[questions]]
pregunta = "Que tipo de direccionamiento es utilizado la capa 2"
respuesta = "mac-address"
opciones = ["ip", "ipx", "tcp"]
    
[[questions]]
pregunta = "Que protocolo de transmission de datos es confiable"
respuesta = "tcp"
opciones = ["udp", "rtp", "tftp"] 