# questions.toml
[[questions]]
pregunta = "Que tipo de dominio separa una VLAN"
respuestas = ["broadcast"]
opciones = ["colision", "multicast", "unicast"]
explicacion = '''
    Las VLAN son capaces de separar dominio de broadcast en un switch
    Entre vlan no hay comunicacion a menos que un router sea colocado
    para interconectarlas.
'''

[[questions]]
pregunta = "Que direccionamiento es utilizado en la capa 3 del modelo OSI"
respuestas = ["ip"]
opciones = ["mac-address", "netbios", "serial"]


[[questions]]
pregunta = "Que dispositivo communta tramas y separa dominios de colision"
respuestas = ["switch"]
opciones = ["router", "hub", "firewall"]
pista = "Un dispositivo de capa 2"


[[questions]]
pregunta = "Que tipo de direccionamiento es utilizado la capa 2"
respuestas = ["mac-address"]
opciones = ["ip", "ipx", "tcp"]
pista = "Viene embedido en la tarjeta de red fisica"

    
[[questions]]
pregunta = "Que protocolo de transmission de datos es confiable"
respuestas = ["tcp"]
opciones = ["udp", "rtp", "tftp"] 
pista = "3 way Handshake"
explicacion = '''
   TCP es seguro porque que tiene acuse de recepcion
   UDP es el best effort 
'''

[[questions]]
pregunta = "Cuales son los dos protocolos que estan en la capa de transporte (elige 2)"
respuestas = ["tcp", "udp"]
opciones = ["ip", "dns", "tftp"]
explicacion = '''
    TCP y UDP estan en la capa de transporte del modelo OSI y TCP/IP 
''' 