# questions.toml
[redes]
label = "redes"

[[redes.questions]]
pregunta = "Que tipo de dominio separa una VLAN"
respuestas = ["broadcast"]
opciones = ["colision", "multicast", "unicast"]
explicacion = '''
    Las VLAN son capaces de separar dominio de broadcast en un switch
    Entre vlan no hay comunicacion a menos que un router sea colocado
    para interconectarlas.
'''

[[redes.questions]]
pregunta = "Que direccionamiento es utilizado en la capa 3 del modelo OSI"
respuestas = ["ip"]
opciones = ["mac-address", "netbios", "serial"]


[[redes.questions]]
pregunta = "Que dispositivo communta tramas y separa dominios de colision"
respuestas = ["switch"]
opciones = ["router", "hub", "firewall"]
pista = "Un dispositivo de capa 2"


[[redes.questions]]
pregunta = "Que tipo de direccionamiento es utilizado la capa 2"
respuestas = ["mac-address"]
opciones = ["ip", "ipx", "tcp"]
pista = "Viene embedido en la tarjeta de red fisica"

    
[[redes.questions]]
pregunta = "Que protocolo de transmission de datos es confiable"
respuestas = ["tcp"]
opciones = ["udp", "rtp", "tftp"] 
pista = "3 way Handshake"
explicacion = '''
   TCP es seguro porque que tiene acuse de recepcion
   UDP es el best effort 
'''

[[redes.questions]]
pregunta = "Cuales son los dos protocolos que estan en la capa de transporte (elige 2)"
respuestas = ["tcp", "udp"]
opciones = ["ip", "dns", "tftp"]
explicacion = '''
    TCP y UDP estan en la capa de transporte del modelo OSI y TCP/IP 
''' 

[seguridad]
label = "seguridad"

[[seguridad.questions]]
pregunta = "De los siguientes cuales no es un ejemplo de amenaza"
respuestas = ["Un computador con informacion sensitiva"]

opciones = [
    "Un desastre natural como huracan", 
    "Un usuario intentando entrar a los servidores", 
    "Un correo maliciso pidiendo informacion sensitiva"
    ]
explicacion = '''
    Un computador con informacion sensitiva no es una amenaza
    mas bien un riesgo 
''' 

[[seguridad.questions]]
pregunta = "Dispositivo donde se aplican politicas de accesos a la red a traves del bloqueo de puertos"
respuestas = ["firewall"]
opciones = ["router", "switch", "proxy"]
pista = "Las politicas de la red" 

[[seguridad.questions]]
pregunta = "Equipo que collecta logs y analiza comportamientos maliciosos"
respuestas = ["siem"]
opciones = ["Firewall", "IDS", "Proxy"]
explicacion = '''
    El siem collecta logs 
''' 